name:                FPSheet
version:             0.1.0.0
github:              "RKlompUU/fpsheet"
license:             BSD3
author:              "Rick Klomp"
maintainer:          "rick93nl@gmail.com"
copyright:           "2018 Rick Klomp"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RKlompUU/fpsheet#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib

executables:
  FPSheet-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FPSheet
